# Generated by Django 5.1.1 on 2024-10-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr7', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
