# Generated by Django 5.1.1 on 2024-10-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr7', '0002_remove_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2, upload_to='pr7/%Y/%m/%d', verbose_name='URL изображения товара'),
            preserve_default=False,
        ),
    ]
