# Generated by Django 5.1.3 on 2024-12-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'Pending'), ('Обработан', 'Processed'), ('Отправлен', 'Shipped'), ('Доставлен', 'Delivered')], max_length=50),
        ),
    ]
